apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: almoghindi/ag-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
<<<<<<< HEAD
=======
    - image: yonraz/ag-user-profiles
      context: user-profile
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.cs"
            dest: .
>>>>>>> 90cf398c56c0b5db335fc966a67b52f59658bbf8

    # - image: yonraz/ag-user-profiles
    #   context: userProfiles
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "**/*.cs"
    #         dest: .
