<<<<<<< HEAD
apiVersion: skaffold/v2beta15
=======
apiVersion: skaffold/v4beta10
>>>>>>> 697c73ab25c5c92b4158cb38ef02dc419371b7e6
kind: Config
build:
  artifacts:
    - image: almoghindi/ag-auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yonraz/ag-user-profiles
      context: user-profile
      sync:
        manual:
          - src: '**/*.cs'
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}